"""Add table for `Report` model.

Revision ID: 3b9f2f6e0d3c
Revises: 3e2e5299576f
Create Date: 2014-06-28 00:21:44.910113

"""

# revision identifiers, used by Alembic.
revision = '3b9f2f6e0d3c'
down_revision = '3e2e5299576f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('har', postgresql.JSON(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_ref'), 'reports', ['ref'], unique=False)
    op.create_index(op.f('ix_reports_url'), 'reports', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_url'), table_name='reports')
    op.drop_index(op.f('ix_reports_ref'), table_name='reports')
    op.drop_table('reports')
    ### end Alembic commands ###
