"""empty message

Revision ID: 3e2e5299576f
Revises: None
Create Date: 2014-06-28 00:21:13.229126

"""

# revision identifiers, used by Alembic.
revision = '3e2e5299576f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
